#!/bin/sh /etc/rc.common
# /etc/init.d/dwtool-traffic
# Modem Traffic Logger service for Dell DW5821e Toolkits

START=96
USE_PROCD=1

start_service() {
	procd_open_instance "main"
	procd_set_param command /bin/sh -c "
		logger -t dwtool-traffic 'Modem Traffic Logger service started'
		while true; do
			# Resolve interface
			direct_interface=\$(uci -q get dwtool.watchdog.direct_interface || echo \"\")
			if [ -z \"\$direct_interface\" ]; then
				for s in \$(uci show network 2>/dev/null | grep \"proto='modemmanager'\" | cut -f2 -d.); do
					direct_interface=\"\$s\"
					break
				done
			fi
			[ -z \"\$direct_interface\" ] && direct_interface=\"wan_dw\"
			
			phys_dev=\$(ubus call network.interface.\"\$direct_interface\" status 2>/dev/null | jsonfilter -e '@.l3_device' 2>/dev/null)
			[ -z \"\$phys_dev\" ] && phys_dev=\"\$direct_interface\"
			
			if [ -n \"\$phys_dev\" ] && [ \"\$phys_dev\" != \"none\" ]; then
				/usr/share/dwtool/traffic_logger.lua \"\$phys_dev\" >/dev/null 2>&1
			fi
			sleep 60
		done
	"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
